$outputPath = Join-Path -Path $PSScriptRoot -ChildPath 'Output\Topology.ServiceMap.png'

New-ImageTopology -TopologyDefinition {
    New-ImageTopologyGroup -Id 'edge' -Label 'Edge Site' -Status Healthy -Symbol region
    New-ImageTopologyNode -Id 'gateway' -Label 'Gateway' -Kind Network -Status Healthy -GroupId 'edge' -Symbol GW
    New-ImageTopologyNode -Id 'api' -Label 'App API' -Kind Service -Status Healthy -GroupId 'edge' -Symbol API
    New-ImageTopologyNode -Id 'database' -Label 'Database' -Kind Database -Status Warning -GroupId 'edge' -Symbol SQL
    New-ImageTopologyEdge -SourceNodeId 'gateway' -TargetNodeId 'api' -Label 'HTTPS' -Kind Connectivity -Status Healthy -Direction Forward
    New-ImageTopologyEdge -SourceNodeId 'api' -TargetNodeId 'database' -Label '32 ms' -Kind Dependency -Status Warning -Direction Forward
} -Title 'Service topology' -Subtitle 'Generated by ImagePlayground + ChartForgeX' -Layout Layered -Direction LeftToRight -Theme Dark -Transparent -Width 900 -Height 480 -FitContentToViewport -FilePath $outputPath
